### ISSUE TITLE
No module named memory

### ISSUE THREAD

**Issue by anazhd** [JRSteeves/PoloniexBot#3]
```
Traceback (most recent call last):
  File "run_poloniex2.py", line 5, in <module>
    from agent import Agent
  File "/home/ubuntu/PoloniexBot/src/agent.py", line 1, in <module>
    from memory import ExperienceReplay
ImportError: No module named memory
```

Please have a look on this, im unable to figure the problem even after looking on the agent.py

**Comment by JRSteeves** [comment]
i'll take a look
